# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_event_body import BaseEventBody  # noqa: F401,E501
from swagger_server.models.event_classifier_code import EventClassifierCode  # noqa: F401,E501
from swagger_server.models.event_created_date_time import EventCreatedDateTime  # noqa: F401,E501
from swagger_server.models.event_date_time import EventDateTime  # noqa: F401,E501
from swagger_server import util


class BaseEvent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event_classifier_code: EventClassifierCode=None, event_date_time: EventDateTime=None, event_created_date_time: EventCreatedDateTime=None):  # noqa: E501
        """BaseEvent - a model defined in Swagger

        :param event_classifier_code: The event_classifier_code of this BaseEvent.  # noqa: E501
        :type event_classifier_code: EventClassifierCode
        :param event_date_time: The event_date_time of this BaseEvent.  # noqa: E501
        :type event_date_time: EventDateTime
        :param event_created_date_time: The event_created_date_time of this BaseEvent.  # noqa: E501
        :type event_created_date_time: EventCreatedDateTime
        """
        self.swagger_types = {
            'event_classifier_code': EventClassifierCode,
            'event_date_time': EventDateTime,
            'event_created_date_time': EventCreatedDateTime
        }

        self.attribute_map = {
            'event_classifier_code': 'eventClassifierCode',
            'event_date_time': 'eventDateTime',
            'event_created_date_time': 'eventCreatedDateTime'
        }
        self._event_classifier_code = event_classifier_code
        self._event_date_time = event_date_time
        self._event_created_date_time = event_created_date_time

    @classmethod
    def from_dict(cls, dikt) -> 'BaseEvent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The baseEvent of this BaseEvent.  # noqa: E501
        :rtype: BaseEvent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_classifier_code(self) -> EventClassifierCode:
        """Gets the event_classifier_code of this BaseEvent.


        :return: The event_classifier_code of this BaseEvent.
        :rtype: EventClassifierCode
        """
        return self._event_classifier_code

    @event_classifier_code.setter
    def event_classifier_code(self, event_classifier_code: EventClassifierCode):
        """Sets the event_classifier_code of this BaseEvent.


        :param event_classifier_code: The event_classifier_code of this BaseEvent.
        :type event_classifier_code: EventClassifierCode
        """
        if event_classifier_code is None:
            raise ValueError("Invalid value for `event_classifier_code`, must not be `None`")  # noqa: E501

        self._event_classifier_code = event_classifier_code

    @property
    def event_date_time(self) -> EventDateTime:
        """Gets the event_date_time of this BaseEvent.


        :return: The event_date_time of this BaseEvent.
        :rtype: EventDateTime
        """
        return self._event_date_time

    @event_date_time.setter
    def event_date_time(self, event_date_time: EventDateTime):
        """Sets the event_date_time of this BaseEvent.


        :param event_date_time: The event_date_time of this BaseEvent.
        :type event_date_time: EventDateTime
        """
        if event_date_time is None:
            raise ValueError("Invalid value for `event_date_time`, must not be `None`")  # noqa: E501

        self._event_date_time = event_date_time

    @property
    def event_created_date_time(self) -> EventCreatedDateTime:
        """Gets the event_created_date_time of this BaseEvent.


        :return: The event_created_date_time of this BaseEvent.
        :rtype: EventCreatedDateTime
        """
        return self._event_created_date_time

    @event_created_date_time.setter
    def event_created_date_time(self, event_created_date_time: EventCreatedDateTime):
        """Sets the event_created_date_time of this BaseEvent.


        :param event_created_date_time: The event_created_date_time of this BaseEvent.
        :type event_created_date_time: EventCreatedDateTime
        """
        if event_created_date_time is None:
            raise ValueError("Invalid value for `event_created_date_time`, must not be `None`")  # noqa: E501

        self._event_created_date_time = event_created_date_time
