# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.equipment_reference import EquipmentReference  # noqa: F401,E501
from swagger_server import util


class EquipmentSubscriptionBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, equipment_reference: EquipmentReference=None):  # noqa: E501
        """EquipmentSubscriptionBody - a model defined in Swagger

        :param equipment_reference: The equipment_reference of this EquipmentSubscriptionBody.  # noqa: E501
        :type equipment_reference: EquipmentReference
        """
        self.swagger_types = {
            'equipment_reference': EquipmentReference
        }

        self.attribute_map = {
            'equipment_reference': 'equipmentReference'
        }
        self._equipment_reference = equipment_reference

    @classmethod
    def from_dict(cls, dikt) -> 'EquipmentSubscriptionBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The equipmentSubscriptionBody of this EquipmentSubscriptionBody.  # noqa: E501
        :rtype: EquipmentSubscriptionBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def equipment_reference(self) -> EquipmentReference:
        """Gets the equipment_reference of this EquipmentSubscriptionBody.


        :return: The equipment_reference of this EquipmentSubscriptionBody.
        :rtype: EquipmentReference
        """
        return self._equipment_reference

    @equipment_reference.setter
    def equipment_reference(self, equipment_reference: EquipmentReference):
        """Sets the equipment_reference of this EquipmentSubscriptionBody.


        :param equipment_reference: The equipment_reference of this EquipmentSubscriptionBody.
        :type equipment_reference: EquipmentReference
        """

        self._equipment_reference = equipment_reference
