# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_event import BaseEvent  # noqa: F401,E501
from swagger_server.models.base_transport_event import BaseTransportEvent  # noqa: F401,E501
from swagger_server.models.change_remark import ChangeRemark  # noqa: F401,E501
from swagger_server.models.delay_reason_code import DelayReasonCode  # noqa: F401,E501
from swagger_server.models.event_created_date_time import EventCreatedDateTime  # noqa: F401,E501
from swagger_server.models.event_date_time import EventDateTime  # noqa: F401,E501
from swagger_server.models.transport_call import TransportCall  # noqa: F401,E501
from swagger_server.models.transport_event_type_code import TransportEventTypeCode  # noqa: F401,E501
from swagger_server import util


class OperationsTransportEvent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event_classifier_code: str=None, transport_event_type_code: TransportEventTypeCode=None, delay_reason_code: DelayReasonCode=None, change_remark: ChangeRemark=None, transport_call: TransportCall=None, event_created_date_time: EventCreatedDateTime=None, event_date_time: EventDateTime=None):  # noqa: E501
        """OperationsTransportEvent - a model defined in Swagger

        :param event_classifier_code: The event_classifier_code of this OperationsTransportEvent.  # noqa: E501
        :type event_classifier_code: str
        :param transport_event_type_code: The transport_event_type_code of this OperationsTransportEvent.  # noqa: E501
        :type transport_event_type_code: TransportEventTypeCode
        :param delay_reason_code: The delay_reason_code of this OperationsTransportEvent.  # noqa: E501
        :type delay_reason_code: DelayReasonCode
        :param change_remark: The change_remark of this OperationsTransportEvent.  # noqa: E501
        :type change_remark: ChangeRemark
        :param transport_call: The transport_call of this OperationsTransportEvent.  # noqa: E501
        :type transport_call: TransportCall
        :param event_created_date_time: The event_created_date_time of this OperationsTransportEvent.  # noqa: E501
        :type event_created_date_time: EventCreatedDateTime
        :param event_date_time: The event_date_time of this OperationsTransportEvent.  # noqa: E501
        :type event_date_time: EventDateTime
        """
        self.swagger_types = {
            'event_classifier_code': str,
            'transport_event_type_code': TransportEventTypeCode,
            'delay_reason_code': DelayReasonCode,
            'change_remark': ChangeRemark,
            'transport_call': TransportCall,
            'event_created_date_time': EventCreatedDateTime,
            'event_date_time': EventDateTime
        }

        self.attribute_map = {
            'event_classifier_code': 'eventClassifierCode',
            'transport_event_type_code': 'transportEventTypeCode',
            'delay_reason_code': 'delayReasonCode',
            'change_remark': 'changeRemark',
            'transport_call': 'transportCall',
            'event_created_date_time': 'eventCreatedDateTime',
            'event_date_time': 'eventDateTime'
        }
        self._event_classifier_code = event_classifier_code
        self._transport_event_type_code = transport_event_type_code
        self._delay_reason_code = delay_reason_code
        self._change_remark = change_remark
        self._transport_call = transport_call
        self._event_created_date_time = event_created_date_time
        self._event_date_time = event_date_time

    @classmethod
    def from_dict(cls, dikt) -> 'OperationsTransportEvent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operationsTransportEvent of this OperationsTransportEvent.  # noqa: E501
        :rtype: OperationsTransportEvent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_classifier_code(self) -> str:
        """Gets the event_classifier_code of this OperationsTransportEvent.

        Code for the event classifier can be - ACT (Actual) - PLN (Planned) - EST (Estimated)   # noqa: E501

        :return: The event_classifier_code of this OperationsTransportEvent.
        :rtype: str
        """
        return self._event_classifier_code

    @event_classifier_code.setter
    def event_classifier_code(self, event_classifier_code: str):
        """Sets the event_classifier_code of this OperationsTransportEvent.

        Code for the event classifier can be - ACT (Actual) - PLN (Planned) - EST (Estimated)   # noqa: E501

        :param event_classifier_code: The event_classifier_code of this OperationsTransportEvent.
        :type event_classifier_code: str
        """
        if event_classifier_code is None:
            raise ValueError("Invalid value for `event_classifier_code`, must not be `None`")  # noqa: E501

        self._event_classifier_code = event_classifier_code

    @property
    def transport_event_type_code(self) -> TransportEventTypeCode:
        """Gets the transport_event_type_code of this OperationsTransportEvent.


        :return: The transport_event_type_code of this OperationsTransportEvent.
        :rtype: TransportEventTypeCode
        """
        return self._transport_event_type_code

    @transport_event_type_code.setter
    def transport_event_type_code(self, transport_event_type_code: TransportEventTypeCode):
        """Sets the transport_event_type_code of this OperationsTransportEvent.


        :param transport_event_type_code: The transport_event_type_code of this OperationsTransportEvent.
        :type transport_event_type_code: TransportEventTypeCode
        """
        if transport_event_type_code is None:
            raise ValueError("Invalid value for `transport_event_type_code`, must not be `None`")  # noqa: E501

        self._transport_event_type_code = transport_event_type_code

    @property
    def delay_reason_code(self) -> DelayReasonCode:
        """Gets the delay_reason_code of this OperationsTransportEvent.


        :return: The delay_reason_code of this OperationsTransportEvent.
        :rtype: DelayReasonCode
        """
        return self._delay_reason_code

    @delay_reason_code.setter
    def delay_reason_code(self, delay_reason_code: DelayReasonCode):
        """Sets the delay_reason_code of this OperationsTransportEvent.


        :param delay_reason_code: The delay_reason_code of this OperationsTransportEvent.
        :type delay_reason_code: DelayReasonCode
        """

        self._delay_reason_code = delay_reason_code

    @property
    def change_remark(self) -> ChangeRemark:
        """Gets the change_remark of this OperationsTransportEvent.


        :return: The change_remark of this OperationsTransportEvent.
        :rtype: ChangeRemark
        """
        return self._change_remark

    @change_remark.setter
    def change_remark(self, change_remark: ChangeRemark):
        """Sets the change_remark of this OperationsTransportEvent.


        :param change_remark: The change_remark of this OperationsTransportEvent.
        :type change_remark: ChangeRemark
        """

        self._change_remark = change_remark

    @property
    def transport_call(self) -> TransportCall:
        """Gets the transport_call of this OperationsTransportEvent.


        :return: The transport_call of this OperationsTransportEvent.
        :rtype: TransportCall
        """
        return self._transport_call

    @transport_call.setter
    def transport_call(self, transport_call: TransportCall):
        """Sets the transport_call of this OperationsTransportEvent.


        :param transport_call: The transport_call of this OperationsTransportEvent.
        :type transport_call: TransportCall
        """
        if transport_call is None:
            raise ValueError("Invalid value for `transport_call`, must not be `None`")  # noqa: E501

        self._transport_call = transport_call

    @property
    def event_created_date_time(self) -> EventCreatedDateTime:
        """Gets the event_created_date_time of this OperationsTransportEvent.


        :return: The event_created_date_time of this OperationsTransportEvent.
        :rtype: EventCreatedDateTime
        """
        return self._event_created_date_time

    @event_created_date_time.setter
    def event_created_date_time(self, event_created_date_time: EventCreatedDateTime):
        """Sets the event_created_date_time of this OperationsTransportEvent.


        :param event_created_date_time: The event_created_date_time of this OperationsTransportEvent.
        :type event_created_date_time: EventCreatedDateTime
        """
        if event_created_date_time is None:
            raise ValueError("Invalid value for `event_created_date_time`, must not be `None`")  # noqa: E501

        self._event_created_date_time = event_created_date_time

    @property
    def event_date_time(self) -> EventDateTime:
        """Gets the event_date_time of this OperationsTransportEvent.


        :return: The event_date_time of this OperationsTransportEvent.
        :rtype: EventDateTime
        """
        return self._event_date_time

    @event_date_time.setter
    def event_date_time(self, event_date_time: EventDateTime):
        """Sets the event_date_time of this OperationsTransportEvent.


        :param event_date_time: The event_date_time of this OperationsTransportEvent.
        :type event_date_time: EventDateTime
        """
        if event_date_time is None:
            raise ValueError("Invalid value for `event_date_time`, must not be `None`")  # noqa: E501

        self._event_date_time = event_date_time
