# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reference import Reference  # noqa: F401,E501
from swagger_server import util


class References(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, references: List[Reference]=None):  # noqa: E501
        """References - a model defined in Swagger

        :param references: The references of this References.  # noqa: E501
        :type references: List[Reference]
        """
        self.swagger_types = {
            'references': List[Reference]
        }

        self.attribute_map = {
            'references': 'references'
        }
        self._references = references

    @classmethod
    def from_dict(cls, dikt) -> 'References':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The references of this References.  # noqa: E501
        :rtype: References
        """
        return util.deserialize_model(dikt, cls)

    @property
    def references(self) -> List[Reference]:
        """Gets the references of this References.


        :return: The references of this References.
        :rtype: List[Reference]
        """
        return self._references

    @references.setter
    def references(self, references: List[Reference]):
        """Sets the references of this References.


        :param references: The references of this References.
        :type references: List[Reference]
        """

        self._references = references
