# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reference_value import ReferenceValue  # noqa: F401,E501
from swagger_server import util


class Reference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reference_value: ReferenceValue=None):  # noqa: E501
        """Reference - a model defined in Swagger

        :param reference_value: The reference_value of this Reference.  # noqa: E501
        :type reference_value: ReferenceValue
        """
        self.swagger_types = {
            'reference_value': ReferenceValue
        }

        self.attribute_map = {
            'reference_value': 'referenceValue'
        }
        self._reference_value = reference_value

    @classmethod
    def from_dict(cls, dikt) -> 'Reference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The reference of this Reference.  # noqa: E501
        :rtype: Reference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reference_value(self) -> ReferenceValue:
        """Gets the reference_value of this Reference.


        :return: The reference_value of this Reference.
        :rtype: ReferenceValue
        """
        return self._reference_value

    @reference_value.setter
    def reference_value(self, reference_value: ReferenceValue):
        """Sets the reference_value of this Reference.


        :param reference_value: The reference_value of this Reference.
        :type reference_value: ReferenceValue
        """
        if reference_value is None:
            raise ValueError("Invalid value for `reference_value`, must not be `None`")  # noqa: E501

        self._reference_value = reference_value
