# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.seal import Seal  # noqa: F401,E501
from swagger_server import util


class Seals(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, seals: List[Seal]=None):  # noqa: E501
        """Seals - a model defined in Swagger

        :param seals: The seals of this Seals.  # noqa: E501
        :type seals: List[Seal]
        """
        self.swagger_types = {
            'seals': List[Seal]
        }

        self.attribute_map = {
            'seals': 'seals'
        }
        self._seals = seals

    @classmethod
    def from_dict(cls, dikt) -> 'Seals':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The seals of this Seals.  # noqa: E501
        :rtype: Seals
        """
        return util.deserialize_model(dikt, cls)

    @property
    def seals(self) -> List[Seal]:
        """Gets the seals of this Seals.


        :return: The seals of this Seals.
        :rtype: List[Seal]
        """
        return self._seals

    @seals.setter
    def seals(self, seals: List[Seal]):
        """Sets the seals of this Seals.


        :param seals: The seals of this Seals.
        :type seals: List[Seal]
        """

        self._seals = seals
