# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SealType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    KLP = "KLP"
    BLT = "BLT"
    WIR = "WIR"
    def __init__(self):  # noqa: E501
        """SealType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SealType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sealType of this SealType.  # noqa: E501
        :rtype: SealType
        """
        return util.deserialize_model(dikt, cls)
