# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ShipmentEventTypeCode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    RECE = "RECE"
    DRFT = "DRFT"
    PENA = "PENA"
    PENU = "PENU"
    REJE = "REJE"
    APPR = "APPR"
    ISSU = "ISSU"
    SURR = "SURR"
    SUBM = "SUBM"
    VOID = "VOID"
    CONF = "CONF"
    def __init__(self):  # noqa: E501
        """ShipmentEventTypeCode - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ShipmentEventTypeCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The shipmentEventTypeCode of this ShipmentEventTypeCode.  # noqa: E501
        :rtype: ShipmentEventTypeCode
        """
        return util.deserialize_model(dikt, cls)
