# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VesselOperatorCarrierCodeListProvider(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SMDG = "SMDG"
    NMFTA = "NMFTA"
    def __init__(self):  # noqa: E501
        """VesselOperatorCarrierCodeListProvider - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VesselOperatorCarrierCodeListProvider':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The vesselOperatorCarrierCodeListProvider of this VesselOperatorCarrierCodeListProvider.  # noqa: E501
        :rtype: VesselOperatorCarrierCodeListProvider
        """
        return util.deserialize_model(dikt, cls)
